// GENERATED by Programme/Flagship/build/build_v3.py — do not hand-edit.
// Therapy+ session materials, served statically from /public/session-NN.

export type PortalResource = {
  href: string;
  label: string;
  open?: boolean;
  sub?: string;
  icon?: string;
};

export const WEEK_WORKBOOK: Record<number, PortalResource | undefined> = {
  1: { href: "/session-01/Session-1-Foundations-Workbook.html", label: "Open your workbook", open: true },
  2: { href: "/session-02/Session-02-Working-Sheet.html", label: "Open your Working Sheet", open: true },
};

export const WEEK_RESOURCES: Record<number, PortalResource[]> = {
  1: [
    { href: "/session-01/Session-01-Principle-Card.html", label: "The Principle Card", sub: "One page · pin it up", icon: "▤", open: true },
    { href: "/session-01/Session-1-Playbook.pdf", label: "The Playbook", sub: "Four reference sheets · PDF", icon: "▤", open: true },
    { href: "/session-01/Resource-Mindset-Reminders-v2.pdf", label: "Mindset Reminders", sub: "Daily prompts · PDF", icon: "◈", open: true },
    { href: "/session-01/Resource-Therapist-to-Coach-Snapshot-v2.pdf", label: "Therapist → Coach Snapshot", sub: "The lens flip at a glance · PDF", icon: "⇄", open: true },
    { href: "/session-01/Session-01-Working-Sheet.html", label: "The updated Working Sheet", sub: "New: the seven shifts, and what could derail you", icon: "◆", open: true },
  ],
  2: [
    { href: "/session-02/Session-02-Principle-Card.html", label: "The Principle Card", sub: "One page · pin it up", icon: "▤", open: true },
  ],
};

export const WEEK_PRINT_RESOURCES: Record<number, PortalResource[]> = {
  1: [
    { href: "/session-01/Session-01-Principle-Card-Print-BW.pdf", label: "The Principle Card", sub: "Ink-friendly · PDF", icon: "▤", open: true },
    { href: "/session-01/Session-1-Playbook-Print-BW.pdf", label: "The Playbook", sub: "Ink-friendly · PDF", icon: "▤", open: true },
    { href: "/session-01/Resource-Mindset-Reminders-Print-BW.pdf", label: "Mindset Reminders", sub: "Ink-friendly · PDF", icon: "▤", open: true },
    { href: "/session-01/Resource-Therapist-to-Coach-Snapshot-Print-BW.pdf", label: "Therapist → Coach Snapshot", sub: "Ink-friendly · PDF", icon: "▤", open: true },
  ],
  2: [
    { href: "/session-02/Session-02-Principle-Card-Print-BW.pdf", label: "The Principle Card", sub: "Ink-friendly · PDF", icon: "▤", open: true },
  ],
};

export function weekWorkbook(n: number) { return WEEK_WORKBOOK[n]; }
export function weekResources(n: number) { return WEEK_RESOURCES[n] ?? []; }
export function weekPrintResources(n: number) { return WEEK_PRINT_RESOURCES[n] ?? []; }
