import type { ReactNode } from "react";

// GENERATED by Programme/Flagship/build/build_v3.py — do not hand-edit.
// Rich per-week copy for the portal's 'this week' experience.

export type BudgetPart = { value: string; label: string };

export type WeekGuide = {
  bannerIntro?: string;
  note?: { fromLabel: string; initial: string; body: ReactNode };
  budget?: { total: string; parts: BudgetPart[] };
  videoStep?: { mins: string; title: string; blurb: ReactNode };
  workbookStep?: { mins: string; title: string; blurb: ReactNode; caveat: ReactNode };
  resourcesStep?: { blurb: string };
};

export const WEEK_GUIDE: Record<number, WeekGuide> = {
  1: {
    bannerIntro: "One question runs through this session: what could derail you on the way to becoming a successful coach? We name it now, while it costs nothing.",
    note: {
      fromLabel: "A Note From Your Coach",
      initial: "D",
      body: (<><span className="block">{"We do this first because it is far easier to handle what could derail you once you have seen it coming."}</span><span className="block mt-3">{"Bring the sheet rough. Half-formed answers and question marks are welcome — you are not meant to finish it alone. We finish it together on the call."}</span><span className="block mt-3">{"And start your contact list. It runs for the next few weeks rather than one evening: add people whenever they come to mind, and keep adding. One rule: your current therapy clients don't go on it."}</span></>),
    },
    budget: { total: "35 minutes, plus your list", parts: [{ value: "9 min", label: "to watch" }, { value: "25 min", label: "for the sheet" }, { value: "ongoing", label: "your list" }] },
    videoStep: {
      mins: "approx 9 min",
      title: "Pre-work video — foundations",
      blurb: (<>{"A walk through your Working Sheet, block by block, so you know exactly what each one is asking."}</>),
    },
    workbookStep: {
      mins: "25 min",
      title: "Your Working Sheet",
      blurb: (<>{"Four blocks, one question: what could derail you? One focused sitting."}</>),
      caveat: (<>{"Your answers save in this browser only. Use Download / print to keep a copy, and send it to me 24 hours before we speak."}</>),
    },
    resourcesStep: { blurb: "Start with the Principle Card; the rest is optional depth." },
  },
  2: {
    bannerIntro: "Generate wide, narrow later, research the last three — then we pick one together on the call.",
    note: {
      fromLabel: "A Note From Your Coach",
      initial: "D",
      body: (<><span className="block">{"More pre-work than most this week, deliberately. Generating and researching are things you can do alone. Deciding is not — that is what our session is for."}</span><span className="block mt-3">{"Do the stages in separate sittings if you can. Generating and judging at once flattens your ideas, and a night’s gap usually produces something you would not have reached in one go."}</span><span className="block mt-3">{"Nothing goes out this week. You need the words before you can tell anyone, and that is the next session — so this week is yours to think in."}</span></>),
    },
    budget: { total: "95 minutes", parts: [{ value: "7 min", label: "to watch" }, { value: "45 min", label: "generating" }, { value: "45 min", label: "researching three" }] },
    videoStep: {
      mins: "approx 7 min",
      title: "Pre-work video — niche",
      blurb: (<>{"What niching actually does for you, the advantage you already have, and a walk through the three stages of your Working Sheet."}</>),
    },
    workbookStep: {
      mins: "25 min",
      title: "Your Working Sheet",
      blurb: (<>{"Three stages, in order: generate everything, narrow it down, then research your top three. Finish each stage before moving on. Do not pick a winner — bring all three and what you found, and we choose together on the call."}</>),
      caveat: (<>{"Your answers save in this browser only. Use Download / print to keep a copy, and send it to me 24 hours before we speak."}</>),
    },
  },
  3: {
    bannerIntro: "Your client is the hero of this story and you are the guide. This session gives you the words — and your announcement goes out at the end of it.",
    note: {
      fromLabel: "A Note From Your Coach",
      initial: "D",
      body: (<><span className="block">{"Read before you write. The people you want to serve talk about their own lives in forums, comment threads and reviews — go and read a few, then put what you found into section two in your own words. Your therapy clients are not a source; that lane stays separate."}</span><span className="block mt-3">{"Quantity first, editing second. Aim for ten lines under each heading — every table takes as many rows as you need."}</span><span className="block mt-3">{"By the end of our next session your announcement goes out. Written together, sent the same day."}</span></>),
    },
    budget: { total: "65 minutes, plus your list", parts: [{ value: "7 min", label: "to watch" }, { value: "60 min", label: "for the sheet" }, { value: "ongoing", label: "your list" }] },
    videoStep: {
      mins: "approx 7 min",
      title: "Pre-work video — message",
      blurb: (<>{"Why your client is the hero and you are the guide, what a guide needs besides empathy, and the five things every message is built from."}</>),
    },
    workbookStep: {
      mins: "60 min",
      title: "Your Working Sheet",
      blurb: (<>{"Four sections. Everything you write later — your website copy, your emails, your outreach, the words inside your own program — starts here, so keep this page and keep adding to it. In section two, aim for ten lines under each heading and add rows until you run out. Do not edit while you write."}</>),
      caveat: (<>{"Your answers save in this browser only. Use Download / print to keep a copy, and send it to me 24 hours before we speak."}</>),
    },
  },
  4: {
    bannerIntro: "Phase two starts here. You move from who you serve to how you serve them, and you build the skeleton of your coaching program.",
    note: {
      fromLabel: "A Note From Your Coach",
      initial: "D",
      body: (<><span className="block">{"Start from your own knowledge and experience. Research fills the gaps afterwards."}</span></>),
    },
    budget: { total: "135 minutes", parts: [{ value: "5 min", label: "to watch" }, { value: "130 min", label: "for the sheet, in three sittings of about 45 minutes" }] },
    videoStep: {
      mins: "approx 5 min",
      title: "Pre-work video — structure",
      blurb: (<>{"The thirteen steps, from the big questions down to units, resources and weeks, with each stage on one slide."}</>),
    },
    workbookStep: {
      mins: "130 min",
      title: "Your Working Sheet",
      blurb: (<>{"Thirteen steps, with a night between each sitting. The sheet walks you through every step, with a worked example above each box. Send it in at least 24 hours before our next call, and bring your announcement draft from the Message sheet."}</>),
      caveat: (<>{"Your answers save in this browser only. Use Download / print to keep a copy, and send it to me 24 hours before we speak."}</>),
    },
  },
  5: {
    bannerIntro: "We build your first session together, in the hour, from a template. There is a floor you only have to clear.",
    note: {
      fromLabel: "A Note From Your Coach",
      initial: "D",
      body: (<><span className="block">{"This session works differently: the slide template already has the gaps marked, you leave the call with it finished, and we send you the file afterwards."}</span><span className="block mt-3">{"So the pre-work is deliberately light. Please do not polish, and please do not open a design tool."}</span><span className="block mt-3">{"One thing to read before we speak, because it is the most important instruction in this program: there is a minimum standard, and once you have cleared it you are finished. Not when it feels finished. When it clears the floor."}</span></>),
    },
    budget: { total: "20 minutes, plus your list", parts: [{ value: "5 min", label: "to watch" }, { value: "15 min", label: "rough first pass" }, { value: "ongoing", label: "your list" }] },
    videoStep: {
      mins: "approx 5 min",
      title: "Pre-work video — creation",
      blurb: (<>{"What your first session is actually for, the minimum it has to contain, and the template we fill in together on the call."}</>),
    },
    workbookStep: {
      mins: "25 min",
      title: "Your Working Sheet",
      blurb: (<>{"This sheet runs in the same order as the template, block for slide, so whichever you open first the other one fills in. Rough first thoughts only — four scruffy lines is a good outcome, and we build the rest together on the call."}</>),
      caveat: (<>{"Your answers save in this browser only. Use Download / print to keep a copy, and send it to me 24 hours before we speak."}</>),
    },
  },
  6: {
    bannerIntro: "The discovery call, step by step — a conversation you are already unusually good at, with a structure for the last ten minutes.",
    note: {
      fromLabel: "A Note From Your Coach",
      initial: "D",
      body: (<><span className="block">{"Most of our session is rehearsal rather than discussion. Come ready to say things out loud."}</span><span className="block mt-3">{"The two parts people find hardest are saying the price and then staying quiet, and answering the two questions that only come up for therapists. We practice both."}</span><span className="block mt-3">{"If you have had any real conversations already, bring what happened — especially the ones that went badly."}</span></>),
    },
    budget: { total: "50 minutes", parts: [{ value: "8 min", label: "to watch" }, { value: "25 min", label: "for the sheet" }, { value: "15 min", label: "out loud" }] },
    videoStep: {
      mins: "approx 8 min",
      title: "Pre-work video — the conversation",
      blurb: (<>{"The discovery call in order, from setting the agenda to asking for the decision — including the price moment and the action-taking discount."}</>),
    },
    workbookStep: {
      mins: "25 min",
      title: "Your Working Sheet",
      blurb: (<>{"This sheet follows the call in order. Write your own version of each step, then read the whole thing aloud twice before our session."}</>),
      caveat: (<>{"Your answers save in this browser only. Use Download / print to keep a copy, and send it to me 24 hours before we speak."}</>),
    },
  },
  7: {
    bannerIntro: "Volume, done properly. The whole list worked — and the number that makes a first client likely rather than lucky.",
    note: {
      fromLabel: "A Note From Your Coach",
      initial: "D",
      body: (<><span className="block">{"This session teaches nothing new. It is about doing more of what you started in session two, systematically, until the numbers work."}</span><span className="block mt-3">{"Come to our session with your list open. We work through it live, and messages go out while we are talking — including the ones you have been putting off."}</span></>),
    },
    budget: { total: "60 minutes", parts: [{ value: "5 min", label: "to watch" }, { value: "15 min", label: "for the sheet" }, { value: "40 min", label: "on your list" }] },
    videoStep: {
      mins: "approx 5 min",
      title: "Pre-work video — launch",
      blurb: (<>{"Where the target number comes from, why connectors do most of the work, and the rhythm that reaches 250 people without taking over your week."}</>),
    },
    workbookStep: {
      mins: "15 min",
      title: "Your Working Sheet",
      blurb: (<>{"Short sheet, busy week. Most of your time goes on the list rather than on this page."}</>),
      caveat: (<>{"Your answers save in this browser only. Use Download / print to keep a copy, and send it to me 24 hours before we speak."}</>),
    },
  },
};

export function weekGuide(weekNumber: number): WeekGuide | undefined {
  return WEEK_GUIDE[weekNumber];
}
