import type { ReactNode } from "react";

// GENERATED by Programme/Flagship/build/build_v3.py — do not hand-edit.
// Rich per-week copy for the portal's 'this week' experience.

export type BudgetPart = { value: string; label: string };

export type WeekGuide = {
  bannerIntro?: string;
  note?: { fromLabel: string; initial: string; body: ReactNode };
  budget?: { total: string; parts: BudgetPart[] };
  videoStep?: { mins: string; title: string; blurb: ReactNode };
  workbookStep?: { mins: string; title: string; blurb: ReactNode; caveat: ReactNode };
  resourcesStep?: { blurb: string };
};

export const WEEK_GUIDE: Record<number, WeekGuide> = {
  1: {
    bannerIntro: "One question runs through this session: what could derail you on the way to becoming a successful coach? We name it now, while it costs nothing.",
    note: {
      fromLabel: "A Note From Your Coach",
      initial: "D",
      body: (<><span className="block">{"This session answers one question: what could derail you on the way to becoming a successful coach? We name those things now, before they arrive, because they are far easier to handle when you have seen them coming."}</span><span className="block mt-3">{"Watch the video first. It walks through the Working Sheet with you, block by block, so nothing on the sheet is a surprise."}</span><span className="block mt-3">{"Then fill the sheet roughly. Half-formed answers and question marks are welcome — you are not meant to finish it alone. We finish it together on the call."}</span><span className="block mt-3">{"And start your contact list. It runs for the next few weeks rather than one evening: add people whenever they come to mind, and keep adding. Anyone counts."}</span></>),
    },
    budget: { total: "30 minutes, plus your list", parts: [{ value: "6 min", label: "to watch" }, { value: "25 min", label: "for the sheet" }, { value: "ongoing", label: "your list" }] },
    videoStep: {
      mins: "approx 6 min",
      title: "Pre-work video — foundations",
      blurb: (<>{"What could derail you, named in advance — and a walk through your Working Sheet so you know exactly what each block is asking."}</>),
    },
    workbookStep: {
      mins: "25 min",
      title: "Your Working Sheet",
      blurb: (<>{"Four blocks, one question: what could derail you? The video walks through each block, so nothing here should be a surprise. One focused sitting, and bring it rough — we finish it together."}</>),
      caveat: (<>{"Your answers save in this browser only. Use Download / print to keep a copy, and send it to me 24 hours before we speak."}</>),
    },
    resourcesStep: { blurb: "The Principle Card is the one to pin up. Everything else here is optional depth." },
  },
  2: {
    bannerIntro: "Generate wide, narrow later, research the last three — then we pick one together on the call.",
    note: {
      fromLabel: "A Note From Your Coach",
      initial: "D",
      body: (<><span className="block">{"This session has more pre-work than most, and that is deliberate. Generating and researching are things you can do alone. Deciding is not — that is what our session is for."}</span><span className="block mt-3">{"The video walks the Working Sheet with you. Three stages, in order: generate everything, narrow it down, then research the last three."}</span><span className="block mt-3">{"Do the stages in separate sittings if you can. Generating and judging at the same time flattens your ideas, and a night’s gap usually produces something you would not have reached in one go."}</span><span className="block mt-3">{"Bring three to the session, with what you found. Do not pick — we pick together, and then we move straight on to your message."}</span><span className="block mt-3">{"Nothing goes out this week. You need the words before you can tell anyone, and that is the next session — so this week is yours to think in."}</span></>),
    },
    budget: { total: "95 minutes", parts: [{ value: "7 min", label: "to watch" }, { value: "45 min", label: "generating" }, { value: "45 min", label: "researching three" }] },
    videoStep: {
      mins: "approx 7 min",
      title: "Pre-work video — niche",
      blurb: (<>{"What niching actually does for you, the advantage you already have, and a walk through the three stages of your Working Sheet."}</>),
    },
    workbookStep: {
      mins: "25 min",
      title: "Your Working Sheet",
      blurb: (<>{"Three stages, in order: generate, narrow, research. Do them in separate sittings if you can. Do not pick — we pick together on the call."}</>),
      caveat: (<>{"Your answers save in this browser only. Use Download / print to keep a copy, and send it to me 24 hours before we speak."}</>),
    },
    resourcesStep: { blurb: "The Principle Card is the one to pin up. Everything else here is optional depth." },
  },
};

export function weekGuide(weekNumber: number): WeekGuide | undefined {
  return WEEK_GUIDE[weekNumber];
}
